services:
  cr-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-default}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs # <-- Sincroniza la carpeta local con el contenedor