# =========================================================
# PRODUCTION ENVIRONMENT (VPS / CLOUD)
# =========================================================

server.port=8080

# Configuración de base de datos (variables de entorno del VPS)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración JPA
# - update = Compara tus clases Java con las tablas. Si falta una columna o tabla, la crea. No borra datos.
# - validate = Solo comprueba si las tablas coinciden con el código Java. Si no coinciden, la app no arranca. No toca nada
# - none = Spring no hace absolutamente nada con la estructura
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=false

# Logging más detallado para debug
logging.level.org.hibernate=debug

# Logging más silencioso
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
