# =========================================================
# DEV ENVIRONMENT (LOCAL DEBUG)
# =========================================================

server.port=8082

# Base de datos local (o contenedor accesible desde localhost)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


# Configuración de JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Logging más detallado para debug
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Logging de HikariCP, ver más detalles
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
